services:
  - type: web
    name: cartoonized-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars: []
    plan: free
    region: oregon
    rootDir: backend
    pythonVersion: 3.10
